
export interface ICruiseLineItemData {
    id: number,
    duration: string,
    name: string,
    year: string,
    port:string,
    destination: string,
    expires: string,
    price:string,
    discountPrice: string
}
export const cruiseLineItemData: ICruiseLineItemData[] = [
    {   id: 1,
        duration: '6  Nights',
        name: 'Mediterranean Highlight Cruise 1',
        year: '11.10.2023',
        port: 'SOUTHAMPTON',
        destination: 'PORTO  . VENICE  .  FLORENCE  .  AMARAFI  .  IBIZA   .  ISTANBUL  .   LISBON   .   SEVILLE   .   DOVER ',
        expires: '07.12.24',
        price:'250pp',
        discountPrice: '215pp'
    },
    {   id: 2,
        duration: '4  Nights',
        name: 'Le Havre Short Break2',
        year: '12.10.2023',
        port: 'Bangladesh',
        destination: 'Dhaka, Rajshahi',
        expires: '09.8.43',
        price:'254pp',
        discountPrice: '155pp'
    },
    {
        id: 3,
        duration: '5  Nights',
        name: 'Le Havre Short Break3',
        year: '13.10.2023',
        port: 'Bangladesh2',
        destination: 'Dhaka, Rajshahi, Khulna',
        expires: '09.8.93',
        price:'254pp',
        discountPrice: '125pp'
    },
    {
        id: 4,
        duration: '6  Nights',
        name: 'Le Havre Short Break4',
        year: '14.10.2023',
        port: 'Bangladesh3',
        destination: 'Rajshahi',
        expires: '09.08.43',
        price:'240pp',
        discountPrice: '185pp'
    },
    {
        id: 5,
        duration: '6  Nights',
        name: 'Le Havre Short Break4',
        year: '15.10.2023',
        port: 'Bangladesh3',
        destination: 'Rajshahi',
        expires: '09.08.43',
        price:'240pp',
        discountPrice: '185pp'
    },
    {
        id: 6,
        duration: '6  Nights',
        name: 'Le Havre Short Break4',
        year: '17.10.2023',
        port: 'Bangladesh3',
        destination: 'Rajshahi',
        expires: '09.08.43',
        price:'240pp',
        discountPrice: '185pp'
    },
    {
        id: 7,
        duration: '6  Nights',
        name: 'Le Havre Short Break4',
        year: '19.10.2023',
        port: 'Bangladesh3',
        destination: 'Rajshahi',
        expires: '09.08.43',
        price:'240pp',
        discountPrice: '185pp'
    },
    {
        id: 8,
        duration: '6  Nights',
        name: 'Le Havre Short Break4',
        year: '20.10.2023',
        port: 'Bangladesh3',
        destination: 'Rajshahi',
        expires: '09.08.43',
        price:'240pp',
        discountPrice: '185pp'
    },
    {
        id: 9,
        duration: '6  Nights',
        name: 'Le Havre Short Break4',
        year: '11.10.2023',
        port: 'Bangladesh3',
        destination: 'Rajshahi',
        expires: '09.08.43',
        price:'240pp',
        discountPrice: '185pp'
    },
    {
        id: 10,
        duration: '6  Nights',
        name: 'Le Havre Short Break4',
        year: '11.10.2023',
        port: 'Bangladesh3',
        destination: 'Rajshahi',
        expires: '09.08.43',
        price:'240pp',
        discountPrice: '185pp'
    },
    {
        id: 12,
        duration: '6  Nights',
        name: 'Le Havre Short Break4',
        year: '11.10.2023',
        port: 'Bangladesh3',
        destination: 'Rajshahi',
        expires: '09.08.43',
        price:'240pp',
        discountPrice: '185pp'
    },
    {  id: 13,
        duration: '6  Nights',
        name: 'Le Havre Short Break4',
        year: '11.10.2023',
        port: 'Bangladesh3',
        destination: 'Rajshahi',
        expires: '09.08.43',
        price:'240pp',
        discountPrice: '185pp'
    },
    {  id: 14,
        duration: '6  Nights',
        name: 'Le Havre Short Break4',
        year: '11.10.2023',
        port: 'Bangladesh3',
        destination: 'Rajshahi',
        expires: '09.08.43',
        price:'240pp',
        discountPrice: '185pp'
    },
    {
        id: 15,
        duration: '6  Nights',
        name: 'Le Havre Short Break4',
        year: '11.10.2023',
        port: 'Bangladesh3',
        destination: 'Rajshahi',
        expires: '09.08.43',
        price:'240pp',
        discountPrice: '185pp'
    },
    {
        id: 16,
        duration: '6  Nights',
        name: 'Le Havre Short Break4',
        year: '11.10.2023',
        port: 'Bangladesh3',
        destination: 'Rajshahi',
        expires: '09.08.43',
        price:'240pp',
        discountPrice: '185pp'
    },
    {
        id: 17,
        duration: '6  Nights',
        name: 'Le Havre Short Break4',
        year: '11.10.2023',
        port: 'Bangladesh3',
        destination: 'Rajshahi',
        expires: '09.08.43',
        price:'240pp',
        discountPrice: '185pp'
    },
    {
        id: 18,
        duration: '6  Nights',
        name: 'Le Havre Short Break4',
        year: '11.10.2023',
        port: 'Bangladesh3',
        destination: 'Rajshahi',
        expires: '09.08.43',
        price:'240pp',
        discountPrice: '185pp'
    },
    {
        id: 19,
        duration: '6  Nights',
        name: 'Le Havre Short Break4',
        year: '11.10.2023',
        port: 'Bangladesh3',
        destination: 'Rajshahi',
        expires: '09.08.43',
        price:'240pp',
        discountPrice: '185pp'
    },
    {
        id:20,
        duration: '6  Nights',
        name: 'Le Havre Short Break4',
        year: '11.10.2023',
        port: 'Bangladesh3',
        destination: 'Rajshahi',
        expires: '09.08.43',
        price:'240pp',
        discountPrice: '185pp'
    },
]