
export interface ICruiseLineItemData {
    id: number,
    duration: string,
    name: string,
    year: string,
    port:string,
    destination: string,
    expires: string,
    price:string,
    discountPrice?: string
}
export const cruiseLineItemData: ICruiseLineItemData[] = [
    {   id: 1,
        duration: '6  Nights',
        name: 'Mediterranean Highlight Cruise 1',
        year: '11.10.2023',
        port: 'SOUTHAMPTON',
        destination: 'PORTO  . VENICE  .  FLORENCE  .  AMARAFI  .  IBIZA   .  ISTANBUL  .   LISBON   .   SEVILLE   .   DOVER ',
        expires: '07.12.24',
        price:'250pp',
        discountPrice: '215pp'
    },
    {   id: 2,
        duration: '4  Nights',
        name: 'Le Havre Short Break2',
        year: '12.10.2023',
        port: 'Bangladesh',
        destination: 'Dhaka, Rajshahi',
        expires: '09.8.43',
        price:'254pp'
    },
    {
        id: 3,
        duration: '5  Nights',
        name: 'Le Havre Short Break3',
        year: '13.10.2023',
        port: 'Bangladesh2',
        destination: 'Dhaka, Rajshahi, Khulna',
        expires: '09.8.93',
        price:'258pp',
        discountPrice: '160pp'
    },
    {
        id: 4,
        duration: '6  Nights',
        name: 'Le Havre Short Break4',
        year: '14.10.2023',
        port: 'Bangladesh3',
        destination: 'Rajshahi',
        expires: '09.08.43',
        price:'260pp',
    },
    {
        id: 5,
        duration: '6  Nights',
        name: 'Le Havre Short Break4',
        year: '15.10.2023',
        port: 'Bangladesh3',
        destination: 'Rajshahi',
        expires: '09.08.43',
        price:'270pp'
    },
    {
        id: 6,
        duration: '6  Nights',
        name: 'Le Havre Short Break4',
        year: '17.10.2023',
        port: 'Bangladesh3',
        destination: 'Rajshahi',
        expires: '09.08.43',
        price:'280pp',
    },
    {
        id: 7,
        duration: '6  Nights',
        name: 'Le Havre Short Break4',
        year: '19.10.2023',
        port: 'Bangladesh3',
        destination: 'Rajshahi',
        expires: '09.08.43',
        price:'290pp',
        discountPrice: '210pp'
    },
    {
        id: 8,
        duration: '6  Nights',
        name: 'Le Havre Short Break4',
        year: '20.10.2023',
        port: 'Bangladesh3',
        destination: 'Rajshahi',
        expires: '09.08.43',
        price:'300pp',
        discountPrice: '285pp'
    },
    {
        id: 9,
        duration: '6  Nights',
        name: 'Le Havre Short Break4',
        year: '11.10.2023',
        port: 'Bangladesh3',
        destination: 'Rajshahi',
        expires: '09.08.43',
        price:'3100pp',
    },
    {
        id: 10,
        duration: '6  Nights',
        name: 'Le Havre Short Break4',
        year: '11.10.2023',
        port: 'Bangladesh3',
        destination: 'Rajshahi',
        expires: '09.08.43',
        price:'320pp',
        discountPrice: '285pp'
    },
    {
        id: 12,
        duration: '6  Nights',
        name: 'Le Havre Short Break4',
        year: '11.10.2023',
        port: 'Bangladesh3',
        destination: 'Rajshahi',
        expires: '09.08.43',
        price:'340pp',
    },
    {  id: 13,
        duration: '6  Nights',
        name: 'Le Havre Short Break4',
        year: '11.10.2023',
        port: 'Bangladesh3',
        destination: 'Rajshahi',
        expires: '09.08.43',
        price:'440pp',
        discountPrice: '385pp'
    },
    {  id: 14,
        duration: '6  Nights',
        name: 'Le Havre Short Break4',
        year: '11.10.2023',
        port: 'Bangladesh3',
        destination: 'Rajshahi',
        expires: '09.08.43',
        price:'380pp',
        discountPrice: '295pp'
    },
    {
        id: 15,
        duration: '6  Nights',
        name: 'Le Havre Short Break4',
        year: '11.10.2023',
        port: 'Bangladesh3',
        destination: 'Rajshahi',
        expires: '09.08.43',
        price:'140pp',
    },
    {
        id: 16,
        duration: '6  Nights',
        name: 'Le Havre Short Break4',
        year: '11.10.2023',
        port: 'Bangladesh3',
        destination: 'Rajshahi',
        expires: '09.08.43',
        price:'170pp',
    },
    {
        id: 17,
        duration: '6  Nights',
        name: 'Le Havre Short Break4',
        year: '11.10.2023',
        port: 'Bangladesh3',
        destination: 'Rajshahi',
        expires: '09.08.43',
        price:'190pp',
        discountPrice: '135pp'
    },
    {
        id: 18,
        duration: '6  Nights',
        name: 'Le Havre Short Break4',
        year: '11.10.2023',
        port: 'Bangladesh3',
        destination: 'Rajshahi',
        expires: '09.08.43',
        price:'350pp',
    },
    {
        id: 19,
        duration: '6  Nights',
        name: 'Le Havre Short Break4',
        year: '11.10.2023',
        port: 'Bangladesh3',
        destination: 'Rajshahi',
        expires: '09.08.43',
        price:'234pp',
        discountPrice: '195pp'
    },
    {
        id:20,
        duration: '6  Nights',
        name: 'Le Havre Short Break4',
        year: '11.10.2023',
        port: 'Bangladesh3',
        destination: 'Rajshahi',
        expires: '09.08.43',
        price:'540pp',
    },
]